DROP TABLE IF EXISTS tb_payment_method CASCADE;
DROP TABLE IF EXISTS tb_price CASCADE;
DROP TABLE IF EXISTS tb_tickets CASCADE;
DROP TABLE IF EXISTS tb_users CASCADE;
DROP TABLE IF EXISTS tb_vehicles CASCADE;
DROP TABLE IF EXISTS user_vehicle CASCADE;

CREATE DATABASE parkingmeter_db;

\c parkingmeter_d;


create table tb_payment_method (
                                   id bigint generated by default as identity,
                                   user_id bigint,
                                   card_expiration_date varchar(255),
                                   card_holder varchar(255),
                                   card_number varchar(255),
                                   cvv varchar(255),
                                   type varchar(255),
                                   primary key (id)
)
    
create table tb_price (
                          hour_price float(53),
                          id bigint generated by default as identity,
                          primary key (id)
)
    
create table tb_tickets (
                            payment_type integer not null,
                            price float(53),
                            card_id bigint,
                            check_in timestamp(6) with time zone,
                            check_out timestamp(6) with time zone,
                            id bigint generated by default as identity,
                            user_id bigint,
                            vehicle_id bigint,
                            pix_code varchar(255),
                            status varchar(255),
                            primary key (id)
)
    
create table tb_users (
                          id bigint generated by default as identity,
                          email varchar(255),
                          name varchar(255),
                          telephone varchar(255),
                          primary key (id)
)
    
create table tb_vehicles (
                             id bigint generated by default as identity,
                             manufacturer varchar(255),
                             model varchar(255),
                             plate varchar(255),
                             primary key (id)
)
    
create table user_vehicle (
                              user_id bigint not null,
                              vehicle_id bigint not null
)
    
alter table if exists tb_tickets
    add constraint FKgpeg54bi17vrqj9p0of0hok2i
    foreign key (card_id)
    references tb_payment_method
    
alter table if exists tb_tickets
    add constraint FKjrl4mno8svm6nnciw3ngrixgj
    foreign key (user_id)
    references tb_users
    
alter table if exists tb_tickets
    add constraint FK308vsl98oub1crkwoqt29clms
    foreign key (vehicle_id)
    references tb_vehicles
    
alter table if exists user_vehicle
    add constraint FK2l91pdf5ombj6hfrqblcqm5d0
    foreign key (vehicle_id)
    references tb_vehicles
    
alter table if exists user_vehicle
    add constraint FKsxkjf3tpiowl75g5b9wukxre5
    foreign key (user_id)
    references tb_users

